### ISSUE TITLE
Invariant Violation 

### ISSUE THREAD

**Issue by waltershub** [iamrajatsoni/DockingBottomSheet#3]
I got this error bellow when trying to use this compompont, I copied the your example 
and passed in the most basic component 

```javascript 
 <View>
  <Text>test</Text>
</View>
```

![File](https://user-images.githubusercontent.com/20269810/73033273-79f8c700-3e0f-11ea-8cf2-a4c6e8989213.jpg)

**Comment by shelojara** [comment]
Did you solve this problem? I'm having the same error.
